// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4p2vUpYj0H_daTLD2_iiBR4doUL5NtQs',
    appId: '1:431916725754:web:69bb30a6539d89bf412043',
    messagingSenderId: '431916725754',
    projectId: 'netes-io',
    authDomain: 'netes-io.firebaseapp.com',
    storageBucket: 'netes-io.firebasestorage.app',
    measurementId: 'G-SPQX2ELR8F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGl0Zxs8ZhHhKQZvb4h6DFE-VGafctwVc',
    appId: '1:431916725754:android:d3fe183990bd76c8412043',
    messagingSenderId: '431916725754',
    projectId: 'netes-io',
    storageBucket: 'netes-io.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK_C_QJKZ5m9Ole0Nk7YVjXzN5KbKkAwA',
    appId: '1:431916725754:ios:d4eb717dcecff9a4412043',
    messagingSenderId: '431916725754',
    projectId: 'netes-io',
    storageBucket: 'netes-io.firebasestorage.app',
    iosBundleId: 'com.example.netes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK_C_QJKZ5m9Ole0Nk7YVjXzN5KbKkAwA',
    appId: '1:431916725754:ios:d4eb717dcecff9a4412043',
    messagingSenderId: '431916725754',
    projectId: 'netes-io',
    storageBucket: 'netes-io.firebasestorage.app',
    iosBundleId: 'com.example.netes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4p2vUpYj0H_daTLD2_iiBR4doUL5NtQs',
    appId: '1:431916725754:web:459b25d568cd6ee1412043',
    messagingSenderId: '431916725754',
    projectId: 'netes-io',
    authDomain: 'netes-io.firebaseapp.com',
    storageBucket: 'netes-io.firebasestorage.app',
    measurementId: 'G-P24H28TR25',
  );

}